### ISSUE TITLE
design: Spacings

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#79]
I will add more, but to get things started:

Please tell me if you need more/other measurements.

### Content: Header Spacings

---
![image](https://user-images.githubusercontent.com/1258870/30597577-aa9df7be-9d57-11e7-9f31-bbdc9607a7b5.png)
---
![image](https://user-images.githubusercontent.com/1258870/30597599-bb366782-9d57-11e7-9562-6cea73b4f203.png)
---

**Comment by kulla** [comment]
Sorry, wrong issue number in commit statement... :see_no_evil:

**Comment by Lodifice** [comment]
Ok, I have spent quite some time with this.

1. KOMA gives us very limited control over spacing.We can `RedeclareSectionCommand` and set all seps to 0pt, but then there is still some space in some cases.
2. What I found is how the sep before or after a section/chapter etc. heading can be set. Is it possible to change your measurement like this? Right now you have context-sensitive line heights, which is not how Tex seems to work.

**Comment by Lodifice** [comment]
I have added a possible implementation in f918d85.

The skips after sections/subsections is `1pt`, smaller is impossible, because `0pt` would put the header and the following paragraph on the same line (only option for smaller skip would be sp instead of pt). There seems to be an automatic skip of a line included if the skip is positive.

I set plus to 1 and minus to 0. For the default values, you can look at the [KOMA manual](http://texdoc.net/texmf-dist/doc/latex/koma-script/scrguide.pdf) (page 441--444).

WHat do you think? What should be different?

**Comment by Lodifice** [comment]
"Fixed" the no space between header and image issue in f223e6ac329276bb7e24bdfef21670c2f61d64b0 by including `vspace` of a `baselineskip`.

As far as I could see, the issue only occurs before `{figure}[h]`s and then consistently, no matter if the thing before is a header or a paragraph.

Is the issue ready to be closed now? :D

**Comment by elbotho** [comment]
👍
