### ISSUE TITLE
Show type of questions

### ISSUE THREAD

**Issue by matipau** [Lodifice/mfnf-pdf-export#88]
Currently, all questions are entitled by "Frage" regardless of their questiontype (e.g. "Verständnisaufgabe"). Instead of "Frage", the questiontype should be shown if it exists.

**Comment by Lodifice** [comment]
Implemented in 958cb3c. Although it was not necessary to add that to 1.0, since "Verständnisfragen" are excluded anyway ;)

**Comment by matipau** [comment]
Thanks for the implementation. I think it is relevant for 1.0, since there are questiontypes other than "Frage" and "Verständnisfrage", e.g. "Verständnisaufgabe" as I already said. Therefore, the current implementation seems wrong to me. The content of the property questiontype should be exported. It could be anything, not only "Verständnisfrage" or not. It is just that if it is "Verständnisfrage" then it is excluded.

**Comment by Lodifice** [comment]
Ok, I mixed "Frage" and "Aufgabe" there. I didn't know there were more types, as this is not documented ;)

I've implemented something like your suggestion in 825ef166d906200e814fde213370ec1bd55799be.

It's not that nice, because now there is more configuration in the Python code and less in the Latex template. For the future, we might want to have an explicit definition of all question types and have them all as different mdtheorems in our Latex template.
