### ISSUE TITLE
design: Boxes finetuning

### ISSUE THREAD

**Issue by elbotho** [Lodifice/mfnf-pdf-export#90]
### Small design update
- [x]	lightblue to 15% of serloblue
- [x]	bar to half the width
- [x] margins stay the same

![image](https://user-images.githubusercontent.com/1258870/31023184-616fd13e-a53b-11e7-8cc0-59c652cab541.png)

### Problems with current implementation
![image](https://user-images.githubusercontent.com/1258870/31022875-6d442aba-a53a-11e7-8e1a-b68726997ead.png)

Independent of titles etc. the blue bar should always start a bit higher and end a little bit lower than the text.
So in the example **"Frage"** needs a top padding and both need a bottom padding.
**"Antwort"** top padding is ok, but could also be ~1pt more.

**Comment by Lodifice** [comment]
Regarding the margin:

The difference is because we do not use mdtheorems for questions anymore, since there is no documentation on what question types there are (see #88).

To fix it manually, I can add 3pt to the `frametitleaboveskip` of questions. Or 4pt, do you have a way to figure that out? In the long run we will come back to using mdtheorems for questions.

In general, this is easy to do. Just give some numbers for top and bottom padding.

Also, please look at important paragraphs. I think they could need some padding, too - maybe the same amount?

**Comment by Lodifice** [comment]
As of 13d4aa71fd6f4b7fe9bd906a729fd3d1be016548, you have changed the width of the line from 5.5pt to 2.75pt. You left the `innerleftmargin` at 5.5pt. So now, the text starts at 8.25pt instead of 11pt. Was this intended?

In aa0fd69e64d5d8d538c1cd02a87759c4783d0de7, I tried to implement the vertical margins. Can you please look if there are still differences in Illustrator? For me, they look good now.

**Comment by elbotho** [comment]
Vertical margins are almost perfect now! 👍 
Sometimes they seem to be variations, but I'd say: Good enough for now!
Can be closed if PR is reviewed.

----
For reference: The first bar ends too early.
![image](https://user-images.githubusercontent.com/1258870/31047348-18fdcc2a-a609-11e7-84f8-4a838f6b776f.png)

**Comment by elbotho** [comment]
with pleasure :)
