### ISSUE TITLE
Online Build - Discussion

### ISSUE THREAD

**Issue by vroland** [Lodifice/mfnf-pdf-export#95]
We should implement an automatic online build for quick (and custom) builds.

**Comment by vroland** [comment]
When building analysis1 python used about ~200MiB RAM at maximum. So a small virtual machine should suffice for now, as we can't even use more than one CPU core.

**Comment by Lodifice** [comment]
The final directory is at 90 MB for me, so disk capacity isn't a limit either.

**Comment by vroland** [comment]
So, what do we need an online build system to do? Do we want users to schedule jobs or just build everythink in a certain time period? How would we handle failed builds? Should users get notified when a build is complete? How much traffic would we expect for this service?

**Comment by Lodifice** [comment]
I'd opt for nightly builds, e.g. a cron job, because that's the most simple solution.

The server should provide the pdf of the last successful build and the last build log. Then we always have a working version and interested user can always look at the details. I think if we define a fixed build time, notifications are not necessary. For developers, we have travis for testing which already sends notifications in the case of failed builds.

I think the traffic is in the order of magnitude of 100 MB per build.
